_format_version: "3.0"
_transform: true

services:
  - name: user-service
    url: http://host.docker.internal:8081
    routes:
      - name: auth-phone
        paths:
          - /auth/phone
        methods:
          - POST
        strip_path: false

      - name: auth-verify
        paths:
          - /auth/verify
        methods:
          - POST
        strip_path: false

      - name: auth-refresh
        paths:
          - /v1/auth/refresh
        methods:
          - POST
        strip_path: false

      - name: user-me
        paths:
          - /v1/me
        methods:
          - GET
        strip_path: false

  - name: rental-service
    url: http://host.docker.internal:8083
    routes:
      - name: rental-create
        paths:
          - /api/v1/rentals
        methods:
          - POST
        strip_path: false

      - name: rental-status
        paths:
          - ~/api/v1/rentals/[^/]+/status
        methods:
          - GET
        strip_path: false

      - name: rental-history
        paths:
          - /api/v1/rentals/history
        methods:
          - GET
        strip_path: false

      - name: rental-finish
        paths:
          - /api/v1/rentals/finish
        methods:
          - POST
        strip_path: false
